window.objetosCifrados = {
  "cama": {
    "1": "DBNB",
    "2": "ECOC",
    "3": "FDPD",
    "4": "GEQE",
    "5": "HFRF",
    "6": "IGSG",
    "7": "JHTH",
    "8": "KIUI",
    "9": "LJVJ",
    "10": "MKWK"
  },
  "escrivaninha": {
    "1": "FTDSJWBOJOIB",
    "2": "GUETKXCPKPJC",
    "3": "HVFULYDQLQKD",
    "4": "IWGVMZERMRLE",
    "5": "JXHWNAFSNSMF",
    "6": "KYIXOBGTOTNG",
    "7": "LZJYPCHUPUOH",
    "8": "MAKZQDIVQVPI",
    "9": "NBLAREJWRWQJ",
    "10": "OCMBSFKXSXRK"
  },
  "cadeira": {
    "1": "DBEFJSB",
    "2": "ECFGKTC",
    "3": "FDGHLUD",
    "4": "GEHIMVE",
    "5": "HFIJNWF",
    "6": "IGJKOXG",
    "7": "JHKLPYH",
    "8": "KILMQZI",
    "9": "LJMNRAJ",
    "10": "MKNOSBK"
  },
  "guarda_roupa": {
    "1": "HVBSEB-SPVQB",
    "2": "IWCTFC-TQWRC",
    "3": "JXDUGD-URXSD",
    "4": "KYEVHE-VSYTE",
    "5": "LZFWIF-WTZUF",
    "6": "MAGXJG-XUAVG",
    "7": "NBHYKH-YVBWH",
    "8": "OCIZLI-ZWCXI",
    "9": "PDJAMJ-AXDYJ",
    "10": "QEKBNK-BYEZK"
  },
  "fogao": {
    "1": "GPHBP",
    "2": "HQICQ",
    "3": "IRJDR",
    "4": "JSKES",
    "5": "KTLFT",
    "6": "LUMGU",
    "7": "MVNHV",
    "8": "NWOIW",
    "9": "OXPJX",
    "10": "PYQKY"
  },
  "mesa_principal": {
    "1": "NFTB",
    "2": "OGUC",
    "3": "PHVD",
    "4": "QIWE",
    "5": "RJXF",
    "6": "SKYG",
    "7": "TLZH",
    "8": "UMAI",
    "9": "VNBJ",
    "10": "WOCK"
  },
  "geladeira": {
    "1": "HFMBEFJSB",
    "2": "IGNCFGKTC",
    "3": "JHODGHLUD",
    "4": "KIPEHIMVE",
    "5": "LJQFIJNWF",
    "6": "MKRGJKOXG",
    "7": "NLSHKLPYH",
    "8": "OMTILMQZI",
    "9": "PNUJMNRAJ",
    "10": "QOVKNOSBK"
  },
  "pia": {
    "1": "QJB",
    "2": "RKC",
    "3": "SLD",
    "4": "TME",
    "5": "UNF",
    "6": "VOG",
    "7": "WPH",
    "8": "XQI",
    "9": "YRJ",
    "10": "ZSK"
  },
  "armario": {
    "1": "BSNBSJP",
    "2": "CTOCTKQ",
    "3": "DUPDULR",
    "4": "EVQEVMS",
    "5": "FWRFWNT",
    "6": "GXSGXOU",
    "7": "HYTHYPV",
    "8": "IZUIZQW",
    "9": "JAVJARX",
    "10": "KBWKBSY"
  },
  "estante": {
    "1": "FTUBOUF",
    "2": "GUVCPVG",
    "3": "HVWDQWH",
    "4": "IWXERXI",
    "5": "JXYFSYJ",
    "6": "KYZGTZK",
    "7": "LZAHUAL",
    "8": "MABIVBM",
    "9": "NBCJWCN",
    "10": "OCDKXDO"
  },
  "janela": {
    "1": "KBOFMB",
    "2": "LCPGNC",
    "3": "MDQHOD",
    "4": "NERIPE",
    "5": "OFSJQF",
    "6": "PGTKRG",
    "7": "QHULSH",
    "8": "RIVMTI",
    "9": "SJWNUJ",
    "10": "TKXOVK"
  },
  "sofa": {
    "1": "TPGB",
    "2": "UQHC",
    "3": "VRID",
    "4": "WSJE",
    "5": "XTKF",
    "6": "YULG",
    "7": "ZVMH",
    "8": "AWNI",
    "9": "BXOJ",
    "10": "CYPK"
  },
  "centro": {
    "1": "DFOUSP",
    "2": "EGPVTQ",
    "3": "FHQWUR",
    "4": "GIRXVS",
    "5": "HJSYWT",
    "6": "IKTZXU",
    "7": "JLUAYV",
    "8": "KMVBZW",
    "9": "LNWCAX",
    "10": "MOXDBY"
  },
  "hack": {
    "1": "IBDL",
    "2": "JCEM",
    "3": "KDFN",
    "4": "LEGO",
    "5": "MFHP",
    "6": "NGIQ",
    "7": "OHJR",
    "8": "PIKS",
    "9": "QJLT",
    "10": "RKMU"
  },
  "privada": {
    "1": "QSJWBEB",
    "2": "RTKXCFC",
    "3": "SULYDGD",
    "4": "TVMZEHE",
    "5": "UWNAFIF",
    "6": "VXOBGJG",
    "7": "WYPCHKH",
    "8": "XZQDILI",
    "9": "YAREJMJ",
    "10": "ZBSFKNK"
  },
  "box": {
    "1": "CPY",
    "2": "DQZ",
    "3": "ERA",
    "4": "FSB",
    "5": "GTC",
    "6": "HUD",
    "7": "IVE",
    "8": "JWF",
    "9": "KXG",
    "10": "LYH"
  },
  "carro": {
    "1": "DBSSP",
    "2": "ECTTQ",
    "3": "FDUUR",
    "4": "GEVVS",
    "5": "HFWWT",
    "6": "IGXXU",
    "7": "JHYYV",
    "8": "KIZZW",
    "9": "LJAAX",
    "10": "MKBBY"
  },
  "tapete": {
    "1": "UBQFUF",
    "2": "VCRGVG",
    "3": "WDSHWH",
    "4": "XETIXI",
    "5": "YFUJYJ",
    "6": "ZGVKZK",
    "7": "AHWLAL",
    "8": "BIXMBM",
    "9": "CJYNCN",
    "10": "DKZODO"
  },
  "poltrona": {
    "1": "QPMUSPOB",
    "2": "RQNVTQPC",
    "3": "SROWURQD",
    "4": "TSPXVSRE",
    "5": "UTQYWTSF",
    "6": "VURZXUTG",
    "7": "WVSAYVUH",
    "8": "XWTBZWVI",
    "9": "YXUCAXWJ",
    "10": "ZYVDBYXK"
  },
  "vaso_planta": {
    "1": "WBTP EF QMBOUB",
    "2": "XCUQ FG RNCPVC",
    "3": "YDVR GH SODQWD",
    "4": "ZEWS HI TPERXE",
    "5": "AFXT IJ UQFSYF",
    "6": "BGYU JK VRGTZG",
    "7": "CHZV KL WSHUAH",
    "8": "DIAW LM XTIVBI",
    "9": "EJBX MN YUJWCJ",
    "10": "FKCY NO ZVKXDK"
  },
  "lavadora": {
    "1": "MBWBEPSB",
    "2": "NCXCFQTC",
    "3": "ODYDGRUD",
    "4": "PEZEHSVE",
    "5": "QFAFITWF",
    "6": "RGBGJUXG",
    "7": "SHCHKVYH",
    "8": "TIDILWZI",
    "9": "UJEJMXAJ",
    "10": "VKFKNYBK"
  },
  "balcao": {
    "1": "CBMDBP",
    "2": "DCNECQ",
    "3": "EDOFDR",
    "4": "FEPGES",
    "5": "GFQHFT",
    "6": "HGRIGU",
    "7": "IHSJHV",
    "8": "JITKIW",
    "9": "KJULJX",
    "10": "LKVMKY"
  },
  "varal": {
    "1": "WBSBM",
    "2": "XCTCN",
    "3": "YDUDO",
    "4": "ZEVEP",
    "5": "AFWFQ",
    "6": "BGXGR",
    "7": "CHYHS",
    "8": "DIZIT",
    "9": "EJAJU",
    "10": "FKBKV"
  },
  "chuveiro": {
    "1": "DIVWFJSP",
    "2": "EJWXGKTQ",
    "3": "FKXYHLUR",
    "4": "GLYZIMVS",
    "5": "HMZAJNWT",
    "6": "INABKOXU",
    "7": "JOBCLPYV",
    "8": "KPCDMQZW",
    "9": "LQDENRAX",
    "10": "MREFOSBY"
  },
  "mesa_lateral": {
    "1": "NFTB MBUFSBM",
    "2": "OGUC NCVGTCN",
    "3": "PHVD ODWHUDO",
    "4": "QIWE PEXIVEP",
    "5": "RJXF QFYJWFQ",
    "6": "SKYG RGZKXGR",
    "7": "TLZH SHALYHS",
    "8": "UMAI TIBMZIT",
    "9": "VNBJ UJCNAJU",
    "10": "WOCK VKDOBKV"
  }
};